eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true 
server:
  port: 9000
  
spring:
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
