spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
     instance-id: instancia3
server:
  port: 8082
  
