server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true 
    
spring:
    mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  h2:
    console:
      enabled: true
